### ISSUE TITLE
Reference to home dir in main.d

### ISSUE THREAD

**Issue by kflak** [chosamuel/openframeworks-physarum#1]
Thank you so much for sharing this! I've been looking for an oF implementation of physarum, and I'm looking very much forward to studying you work on this.

In order to build this, I needed to remove the obj/ directory. Maybe you could add this to .gitignore?

**Comment by somecho** [comment]
Hi! I'm glad it helps you. This was from when I just started c++ so I didn't know much about those. I cleaned up the directory. It needs to be updated by the Project Generator for the respective OS (I'm now no longer on Linux). 

Let me know if it runs properly!
